import { useState } from 'react';
import { BrowserRouter, Link, NavLink, Navigate, Route, Routes, useNavigate } from 'react-router-dom';
import { api } from './api.js';

const getSession = () => JSON.parse(localStorage.getItem('hunarhub-session') || 'null');
function Layout({ children, session, onLogout }) {
  return <><nav className="navbar navbar-expand-lg navbar-dark bg-success shadow-sm"><div className="container"><Link className="navbar-brand fw-bold" to="/">HunarHub</Link><button className="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#nav"><span className="navbar-toggler-icon" /></button><div className="collapse navbar-collapse" id="nav"><div className="navbar-nav ms-auto align-items-lg-center">{session ? <><NavLink className="nav-link" to="/dashboard">My area</NavLink><button className="btn btn-sm btn-light ms-lg-2" onClick={onLogout}>Log out</button></> : <><NavLink className="nav-link" to="/login">Log in</NavLink><NavLink className="btn btn-sm btn-light ms-lg-2" to="/register">Join HunarHub</NavLink></>}</div></div></div></nav>{children}<footer className="border-top py-4 text-center text-secondary small">HunarHub · Supporting local skills and livelihoods</footer></>;
}
function Home() { return <main><section className="hero py-5"><div className="container py-lg-5"><div className="row align-items-center g-4"><div className="col-lg-7"><p className="text-success fw-semibold mb-2">LOCAL SKILLS, MADE VISIBLE</p><h1 className="display-5 fw-bold">Discover the people who make your community special.</h1><p className="lead text-secondary">HunarHub connects customers with talented cobblers, potters, tailors, artisans, and small vendors.</p><Link className="btn btn-success btn-lg" to="/register">Explore HunarHub</Link></div><div className="col-lg-5"><div className="p-4 bg-white rounded-4 shadow-sm"><h2 className="h4">Built for local enterprise</h2><div className="row g-3 mt-1"><Feature title="Find skills" text="Browse local crafts and services." /><Feature title="Offer your work" text="Create a trusted business presence." /><Feature title="Grow together" text="Simple, direct connections." /></div></div></div></div></div></section><section className="container py-5"><h2 className="h3 text-center mb-4">Coming next</h2><div className="row g-3">{['Browse verified entrepreneurs', 'Request local services', 'Shop handmade products'].map((item) => <div className="col-md-4" key={item}><div className="card h-100 border-0 shadow-sm"><div className="card-body"><h3 className="h5">{item}</h3><p className="mb-0 text-secondary">Marketplace features are being prepared in the next stage.</p></div></div></div>)}</div></section></main>; }
function Feature({ title, text }) { return <div className="col-12"><strong>{title}</strong><div className="text-secondary small">{text}</div></div>; }
function AuthForm({ register = false, onSession }) { const [form, setForm] = useState({ name: '', email: '', password: '', role: 'customer' }); const [error, setError] = useState(''); const [busy, setBusy] = useState(false); const navigate = useNavigate(); const submit = async (event) => { event.preventDefault(); setBusy(true); setError(''); try { const data = await api(register ? '/auth/register' : '/auth/login', { method: 'POST', body: JSON.stringify(register ? form : { email: form.email, password: form.password }) }); onSession(data); navigate('/dashboard'); } catch (err) { setError(err.message); } finally { setBusy(false); } }; return <main className="container py-5"><div className="auth-card card border-0 shadow-sm mx-auto"><div className="card-body p-4 p-md-5"><h1 className="h2">{register ? 'Join HunarHub' : 'Welcome back'}</h1><p className="text-secondary">{register ? 'Create a customer or entrepreneur account.' : 'Log in to continue.'}</p>{error && <div className="alert alert-danger">{error}</div>}<form onSubmit={submit} noValidate>{register && <><label className="form-label" htmlFor="name">Full name</label><input id="name" required minLength="2" className="form-control mb-3" value={form.name} onChange={(e) => setForm({ ...form, name: e.target.value })} /></>}<label className="form-label" htmlFor="email">Email address</label><input id="email" type="email" required className="form-control mb-3" value={form.email} onChange={(e) => setForm({ ...form, email: e.target.value })} /><label className="form-label" htmlFor="password">Password</label><input id="password" type="password" minLength="8" required className="form-control mb-3" value={form.password} onChange={(e) => setForm({ ...form, password: e.target.value })} />{register && <><label className="form-label">I want to</label><select className="form-select mb-4" value={form.role} onChange={(e) => setForm({ ...form, role: e.target.value })}><option value="customer">Find products and services</option><option value="entrepreneur">Offer my skills and products</option></select></>}<button disabled={busy} className="btn btn-success w-100">{busy ? 'Please wait…' : register ? 'Create account' : 'Log in'}</button></form><p className="text-center small mt-4 mb-0">{register ? <>Already a member? <Link to="/login">Log in</Link></> : <>New here? <Link to="/register">Create an account</Link></>}</p></div></div></main>; }
function Dashboard({ session }) { if (!session) return <Navigate to="/login" replace />; const { user, verificationStatus } = session; return <main className="container py-5"><div className="p-4 p-md-5 bg-white rounded-4 shadow-sm"><p className="text-success fw-semibold">SIGNED IN AS {user.role.toUpperCase()}</p><h1 className="h2">Hello, {user.name}.</h1><p className="text-secondary mb-0">{user.role === 'entrepreneur' ? `Your entrepreneur account is ${verificationStatus || 'pending'} verification. Profile, products, and requests arrive in the next marketplace stage.` : 'Your account is ready. Entrepreneur browsing, orders, and service requests arrive in the next marketplace stage.'}</p></div></main>; }
function AppRoutes() { const [session, setSession] = useState(getSession); const saveSession = (data) => { localStorage.setItem('hunarhub-session', JSON.stringify(data)); setSession(data); }; const logout = () => { localStorage.removeItem('hunarhub-session'); setSession(null); }; return <Layout session={session} onLogout={logout}><Routes><Route path="/" element={<Home />} /><Route path="/login" element={<AuthForm onSession={saveSession} />} /><Route path="/register" element={<AuthForm register onSession={saveSession} />} /><Route path="/dashboard" element={<Dashboard session={session} />} /><Route path="*" element={<Navigate to="/" replace />} /></Routes></Layout>; }
export default function App() { return <BrowserRouter><AppRoutes /></BrowserRouter>; }
