import { useEffect, useState } from 'react';
import { api } from './api.js';

const blankListing = { kind: 'service', name: '', description: '', price: '', category: '', stock: 1, images: '' };

export function ProfileEditor({ profile, onSaved }) {
  const [categories, setCategories] = useState([]);
  const [form, setForm] = useState({ businessName: '', location: '', bio: '', experience: 0, profileImage: '', skills: [] });
  const [message, setMessage] = useState('');
  const [error, setError] = useState('');
  useEffect(() => { api('/categories').then(setCategories).catch((e) => setError(e.message)); }, []);
  useEffect(() => { if (profile) setForm({ businessName: profile.businessName || '', location: profile.location || '', bio: profile.bio || '', experience: profile.experience || 0, profileImage: profile.profileImage || '', skills: profile.skills?.map((skill) => skill._id) || [] }); }, [profile]);
  const submit = async (event) => { event.preventDefault(); setError(''); try { await api('/entrepreneurs/me', { method: 'PUT', body: JSON.stringify({ ...form, experience: Number(form.experience) }) }); setMessage('Profile saved.'); onSaved(); } catch (e) { setError(e.message); } };
  return <section className="dashboard-section"><div className="section-title"><h2>Business profile</h2><span>Shown to customers after approval</span></div><form className="panel compact" onSubmit={submit}><div className="form-grid"><label className="field">Business name<input value={form.businessName} onChange={(e) => setForm({ ...form, businessName: e.target.value })} maxLength="120"/></label><label className="field">Location<input value={form.location} onChange={(e) => setForm({ ...form, location: e.target.value })} maxLength="120"/></label><label className="field">Years of experience<input type="number" min="0" max="80" value={form.experience} onChange={(e) => setForm({ ...form, experience: e.target.value })}/></label><label className="field">Profile image URL (optional)<input type="url" value={form.profileImage} onChange={(e) => setForm({ ...form, profileImage: e.target.value })}/></label></div><label className="field">About your work<textarea value={form.bio} onChange={(e) => setForm({ ...form, bio: e.target.value })} maxLength="1000"/></label><label className="field">Skills / categories<select multiple value={form.skills} onChange={(e) => setForm({ ...form, skills: [...e.target.selectedOptions].map((item) => item.value) })}>{categories.map((category) => <option key={category._id} value={category._id}>{category.name}</option>)}</select><small>Hold Ctrl/Cmd to choose more than one.</small></label>{error && <div className="notice error">{error}</div>}{message && <div className="notice success">{message}</div>}<button className="btn btn-primary">Save profile</button></form></section>;
}

export function ManageListings() {
  const [categories, setCategories] = useState([]); const [services, setServices] = useState([]); const [products, setProducts] = useState([]); const [form, setForm] = useState(blankListing); const [editing, setEditing] = useState(null); const [error, setError] = useState(''); const [message, setMessage] = useState('');
  const load = async () => { try { const [a, b, c] = await Promise.all([api('/categories'), api('/services/mine'), api('/products/mine')]); setCategories(a); setServices(b); setProducts(c); } catch (e) { setError(e.message); } };
  useEffect(() => { load(); }, []);
  const reset = () => { setEditing(null); setForm(blankListing); };
  const save = async (event) => { event.preventDefault(); setError(''); const payload = { name: form.name, description: form.description, price: Number(form.price), category: form.category, ...(form.kind === 'product' ? { stock: Number(form.stock), images: form.images.split('\n').map((x) => x.trim()).filter(Boolean) } : {}) }; try { await api(`/${form.kind}s${editing ? `/${editing}` : ''}`, { method: editing ? 'PUT' : 'POST', body: JSON.stringify(payload) }); setMessage(editing ? 'Listing updated.' : 'Listing added.'); reset(); load(); } catch (e) { setError(e.message); } };
  const edit = (item, kind) => { setEditing(item._id); setForm({ kind, name: item.name, description: item.description || '', price: item.price, category: item.category?._id || item.category, stock: item.stock ?? 1, images: item.images?.join('\n') || '' }); };
  const remove = async (item, kind) => { if (!window.confirm(`Delete ${item.name}?`)) return; try { await api(`/${kind}s/${item._id}`, { method: 'DELETE' }); setMessage('Listing deleted.'); load(); } catch (e) { setError(e.message); } };
  const toggle = async (item, kind) => { try { await api(`/${kind}s/${item._id}`, { method: 'PUT', body: JSON.stringify({ isAvailable: !item.isAvailable }) }); load(); } catch (e) { setError(e.message); } };
  const rows = [...services.map((item) => ({ ...item, kind: 'service' })), ...products.map((item) => ({ ...item, kind: 'product' }))];
  return <section className="dashboard-section"><div className="section-title"><h2>My listings</h2><span>{rows.length}</span></div><div className="listing-layout"><form className="panel compact" onSubmit={save}><h3>{editing ? 'Edit listing' : 'Add a listing'}</h3><label className="field">Listing type<select disabled={Boolean(editing)} value={form.kind} onChange={(e) => setForm({ ...form, kind: e.target.value })}><option value="service">Service</option><option value="product">Product</option></select></label><label className="field">Name<input required value={form.name} onChange={(e) => setForm({ ...form, name: e.target.value })}/></label><label className="field">Description<textarea value={form.description} onChange={(e) => setForm({ ...form, description: e.target.value })}/></label><div className="form-grid"><label className="field">Price<input required type="number" min="0" value={form.price} onChange={(e) => setForm({ ...form, price: e.target.value })}/></label>{form.kind === 'product' && <label className="field">Stock<input required type="number" min="0" value={form.stock} onChange={(e) => setForm({ ...form, stock: e.target.value })}/></label>}</div><label className="field">Category<select required value={form.category} onChange={(e) => setForm({ ...form, category: e.target.value })}><option value="">Choose category</option>{categories.map((category) => <option key={category._id} value={category._id}>{category.name}</option>)}</select></label>{form.kind === 'product' && <label className="field">Product image URLs (one per line)<textarea value={form.images} onChange={(e) => setForm({ ...form, images: e.target.value })} placeholder="https://example.com/product.jpg"/></label>}{error && <div className="notice error">{error}</div>}{message && <div className="notice success">{message}</div>}<div className="actions"><button className="btn btn-primary">{editing ? 'Save changes' : 'Add listing'}</button>{editing && <button className="btn btn-quiet" type="button" onClick={reset}>Cancel</button>}</div></form><div className="listing-summary"><h3>Current listings</h3>{rows.length ? rows.map((item) => <div key={item._id}><span><b>{item.name}</b><br/>{item.kind} · ₹{item.price}{item.kind === 'product' ? ` · ${item.stock} in stock` : ''} · {item.isAvailable ? 'Available' : 'Hidden'}</span><span className="actions"><button className="text-link button-link" onClick={() => edit(item, item.kind)}>Edit</button><button className="text-link button-link" onClick={() => toggle(item, item.kind)}>{item.isAvailable ? 'Hide' : 'Show'}</button><button className="text-link button-link" onClick={() => remove(item, item.kind)}>Delete</button></span></div>) : <p>No listings yet.</p>}</div></div></section>;
}
